-- Acquisition Quality Analysis
-- Goal:
-- Compare the purchase behavior and revenue generated by users
-- assigned to their first observed acquisition medium.

WITH ranked_events AS (
    SELECT
        user_pseudo_id,
        traffic_source.medium AS medium,
        event_timestamp,
        ROW_NUMBER() OVER (
            PARTITION BY user_pseudo_id
            ORDER BY event_timestamp
        ) AS rn
    FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
),

-- Assign each user to one first-observed medium
first_medium AS (
    SELECT
        user_pseudo_id,
        medium
    FROM ranked_events
    WHERE rn = 1
),

-- Calculate purchase behavior at user level
user_metrics AS (
    SELECT
        user_pseudo_id,
        MAX(
            CASE
                WHEN event_name = 'purchase' THEN 1
                ELSE 0
            END ) AS purchased,
        SUM(
            CASE
                WHEN event_name = 'purchase'
                THEN COALESCE(ecommerce.purchase_revenue, 0)
                ELSE 0
            END ) AS user_revenue
    FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
    GROUP BY user_pseudo_id
),

-- Combine acquisition medium and user value
user_level AS (
    SELECT
        f.user_pseudo_id,
        f.medium,
        COALESCE(u.purchased, 0) AS purchased,
        COALESCE(u.user_revenue, 0) AS user_revenue
    FROM first_medium AS f
    LEFT JOIN user_metrics AS u
        ON f.user_pseudo_id = u.user_pseudo_id
),

-- Aggregate users to medium level
medium_metrics AS (
    SELECT
        medium,
        COUNT(user_pseudo_id) AS users,
        SUM(purchased) AS buyers,
        SUM(user_revenue) AS revenue
    FROM user_level
    GROUP BY medium
)

SELECT
    medium,
    users,
    buyers,
    revenue,
    SAFE_DIVIDE(buyers, users) * 100 AS purchase_rate,
    SAFE_DIVIDE(revenue, users) AS revenue_per_user
FROM medium_metrics
ORDER BY revenue_per_user DESC;
